stages: 
    - produceHistosDataCards
    


variables:
  GIT_DEPTH: "3"


before_script:
    - export CI_HOME=${CI_PROJECT_DIR}
    - echo "Gitlab User: " ${GITLAB_USER_ID}
    - export SCRAM_ARCH="slc6_amd64_gcc530"
    - export CMSSW_VERSION="CMSSW_8_0_26_patch2"
    - source /cvmfs/cms.cern.ch/cmsset_default.sh
    - mkdir -p /nfs/dust/cms/user/${USER}/gitlab-ci
    - cd /nfs/dust/cms/user/${USER}/gitlab-ci
    - scramv1 project CMSSW $CMSSW_VERSION
    - cd $CMSSW_VERSION/src
    - eval `scramv1 runtime -sh`
    - cd $CI_HOME
    
plot_LimitsSpring17v3:
    tags:
        - naf
        - ssh
    stage: produceHistosDataCards
    script:
        - echo "Gitlab User: " ${GITLAB_USER_ID}
        - set -x 
        - cd $CI_HOME
        - python plot_LimitsSpring17v3.py
        - set +x
    when: manual
    allow_failure: false
    artifacts:     
        paths:       
            - $CI_HOME/limits_Spring17v8/*.pdf
        name: plot_LimitsSpring17v3-${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
        expire_in: 1 week
        
