stages: 
    - produceHistosDataCards
    


variables:
  GIT_DEPTH: "3"


before_script:
    - set -x
    - export CI_HOME=${CI_PROJECT_DIR}
    - export SCRAM_ARCH="slc6_amd64_gcc530"
    - export CMSSW_VERSION="CMSSW_8_0_26_patch2"
    - source /cvmfs/cms.cern.ch/cmsset_default.sh
    - mkdir -p /nfs/dust/cms/user/${USER}/gitlab-ci
    - cd /nfs/dust/cms/user/${USER}/gitlab-ci
    - scramv1 project CMSSW $CMSSW_VERSION
    - cd $CMSSW_VERSION/src
    - eval `scramv1 runtime -sh`
    - cd $CI_HOME
    
plot_LimitsSpring17v3:
    tags:
        - naf
        - ssh
        - naf6
    stage: produceHistosDataCards
    script: 
        - cd $CI_HOME/pyroot-plotscripts
        - python plot_LimitsSpring17v3.py
    artifacts:     
        paths:       
            - $CI_HOME/pyroot-plotscripts/limits_Spring17v8/*
        name: plot_LimitsSpring17v3-${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
        expire_in: 1 week
        
