def getAddVars():
    addVars = [
        "Jet_Pt",
        "Muon_Pt",
        "Electron_Pt",
        "Jet_Eta",
        "Muon_Eta",
        "Electron_Eta",
        "Muon_Pt_BeForeRC",
        "Electron_Pt_BeforeRun2Calibration",
        "Electron_Eta_Supercluster",
        "Jet_CSV",
        "Jet_Flav",
        "N_Jets",
        "Jet_E",
        "Jet_Phi",
        "Jet_M",
        "Evt_Pt_PrimaryLepton:=LooseLepton_Pt[0]",
        "Evt_E_PrimaryLepton:=LooseLepton_E[0]",
        "Evt_M_PrimaryLepton:=LooseLepton_M[0]",
        "Evt_Phi_PrimaryLepton:=LooseLepton_Phi[0]",
        "Evt_Eta_PrimaryLepton:=LooseLepton_Eta[0]",
        "Evt_Pt_MET:=Evt_MET_Pt",
        "Weight_CSV",
        "Weight_CSVLFup",
        "Weight_CSVLFdown",
        "Weight_CSVHFup",
        "Weight_CSVHFdown",
        "Weight_CSVHFStats1up",
        "Weight_CSVHFStats1down",
        "Weight_CSVLFStats1down",
        "Weight_CSVHFStats2up",
        "Weight_CSVHFStats2down",
        "Weight_CSVLFStats2up",
        "Weight_CSVLFStats2down",
        "Weight_CSVCErr1down",
        "Weight_CSVCErr2up",
        "Weight_CSVCErr2down",
        "Weight_pu69p2",
        "GenWeight_isr_Def_down:=GenWeight_8",
        "GenWeight_isr_Def_up:=GenWeight_6",
        "GenWeight_fsr_Def_down:=GenWeight_9",
        "GenWeight_fsr_Def_up:=GenWeight_7",
    
        #"discrete_CSV_0:=((CSV[0]>=0.0494)*1+(CSV[0]>=0.277)*1+(CSV[0]>=0.7264)*1)",
        #"discrete_CSV_1:=((CSV[1]>=0.0494)*1+(CSV[1]>=0.277)*1+(CSV[1]>=0.7264)*1)",
        #"discrete_CSV_2:=((CSV[2]>=0.0494)*1+(CSV[2]>=0.277)*1+(CSV[2]>=0.7264)*1)",
        #"discrete_CSV_3:=((CSV[3]>=0.0494)*1+(CSV[3]>=0.277)*1+(CSV[3]>=0.7264)*1)",
        #"discrete_CSV_4:=((CSV[4]>=0.0494)*1+(CSV[4]>=0.277)*1+(CSV[4]>=0.7264)*1)",
        #"discrete_CSV_5:=((CSV[5]>=0.0494)*1+(CSV[5]>=0.277)*1+(CSV[5]>=0.7264)*1)",
        ]

    return addVars


