def getAddVars():
    BDTWeightPath = "/nfs/dust/cms/user/kelmorab/Spring17BDTWeights/"
    BDTSet = "Spring17v1"
    #alternativeBDTSet = "Spring17v3_ttbb"

    addVars = [
        # "Jet_Pt",
        # "Muon_Pt",
        # "Electron_Pt",
        # "Jet_Eta",
        # "Muon_Eta",
        # "Electron_Eta",
        # "Muon_Pt_BeForeRC",
        # "Electron_Pt_BeforeRun2Calibration",
        # "Electron_Eta_Supercluster",
        # "Jet_CSV",
        # "Jet_Flav",
        # "N_Jets",
        # "Jet_E",
        # "Jet_Phi",
        # "Jet_M",
        # "Evt_Pt_PrimaryLepton",
        # "Evt_E_PrimaryLepton",
        # "Evt_M_PrimaryLepton",
        # "Evt_Phi_PrimaryLepton",
        # "Evt_Eta_PrimaryLepton",
        # "Evt_Pt_MET",
        # "Weight_CSV",
        # "Weight_CSVLFup",
        # "Weight_CSVLFdown",
        # "Weight_CSVHFup",
        # "Weight_CSVHFdown",
        # "Weight_CSVHFStats1up",
        # "Weight_CSVHFStats1down",
        # "Weight_CSVLFStats1down",
        # "Weight_CSVHFStats2up",
        # "Weight_CSVHFStats2down",
        # "Weight_CSVLFStats2up",
        # "Weight_CSVLFStats2down",
        # "Weight_CSVCErr1down",
        # "Weight_CSVCErr2up",
        # "Weight_CSVCErr2down",
        # "Evt_blr_ETH",
        # "Evt_blr_ETH_transformed",
        #'finalbdt_ljets_j4_t2:=Evt_HT_Jets',
        #'finalbdt_ljets_j5_t2:=Evt_HT_Jets',
        #'finalbdt_ljets_j4_t3:='+BDTWeightPath+'/weights_Final_43_'+BDTSet+'.xml',
        #'finalbdt_ljets_j4_t4:='+BDTWeightPath+'/weights_Final_44_'+BDTSet+'.xml',
        #'finalbdt_ljets_j5_t3:='+BDTWeightPath+'/weights_Final_53_'+BDTSet+'.xml',
        #'finalbdt_ljets_j5_tge4:='+BDTWeightPath+'/weights_Final_54_'+BDTSet+'.xml',
        #'finalbdt_ljets_jge6_t2:='+BDTWeightPath+'/weights_Final_62_'+BDTSet+'.xml',
        #'finalbdt_ljets_jge6_t3:='+BDTWeightPath+'/weights_Final_63_'+BDTSet+'.xml',
        #'finalbdt_ljets_jge6_tge4:='+BDTWeightPath+'/weights_Final_64_'+BDTSet+'.xml',
        ]

    return addVars
