def getAddVars():
    addVars = [
        "Jet_Pt",
        "Muon_Pt",
        "Electron_Pt",
        "Jet_Eta",
        "Muon_Eta",
        "Electron_Eta",
        "Muon_Pt_BeForeRC",
        "Electron_Pt_BeforeRun2Calibration",
        "Electron_Eta_Supercluster",
        "Jet_CSV",
        "Jet_Flav",
        "N_Jets",
        "Jet_E",
        "Jet_Phi",
        "Jet_M",
        "Evt_Pt_PrimaryLepton",
        "Evt_E_PrimaryLepton",
        "Evt_M_PrimaryLepton",
        "Evt_Phi_PrimaryLepton",
        "Evt_Eta_PrimaryLepton",
        "Evt_Pt_MET",
        "Weight_CSV",
        "Weight_CSVLFup",
        "Weight_CSVLFdown",
        "Weight_CSVHFup",
        "Weight_CSVHFdown",
        "Weight_CSVHFStats1up",
        "Weight_CSVHFStats1down",
        "Weight_CSVLFStats1down",
        "Weight_CSVHFStats2up",
        "Weight_CSVHFStats2down",
        "Weight_CSVLFStats2up",
        "Weight_CSVLFStats2down",
        "Weight_CSVCErr1down",
        "Weight_CSVCErr2up",
        "Weight_CSVCErr2down",
        "Evt_blr_ETH",
        "Evt_blr_ETH_transformed",
        "L1ScaleFactor_j4_tge3_ttHnode:=((DoWeights==1)*(isTthSample==1)*0.976+(DoWeights==1)*(isTthSample==0)*0.979+(DoWeights==0)*1.0)",
        "L1ScaleFactor_j4_tge3_ttbbnode:=((DoWeights==1)*(isTthSample==1)*0.973+(DoWeights==1)*(isTthSample==0)*0.975+(DoWeights==0)*1.0)",
        "L1ScaleFactor_j4_tge3_ttbnode:=((DoWeights==1)*(isTthSample==1)*0.978+(DoWeights==1)*(isTthSample==0)*0.979+(DoWeights==0)*1.0)",
        "L1ScaleFactor_j4_tge3_tt2bnode:=((DoWeights==1)*(isTthSample==1)*0.971+(DoWeights==1)*(isTthSample==0)*0.972+(DoWeights==0)*1.0)",
        "L1ScaleFactor_j4_tge3_ttccnode:=((DoWeights==1)*(isTthSample==1)*0.97+(DoWeights==1)*(isTthSample==0)*0.974+(DoWeights==0)*1.0)",
        "L1ScaleFactor_j4_tge3_ttlfnode:=((DoWeights==1)*(isTthSample==1)*0.974+(DoWeights==1)*(isTthSample==0)*0.983+(DoWeights==0)*1.0)",

        "L1ScaleFactor_j5_tge3_ttHnode:=((DoWeights==1)*(isTthSample==1)*0.979+(DoWeights==1)*(isTthSample==0)*0.976+(DoWeights==0)*1.0)",
        "L1ScaleFactor_j5_tge3_ttbbnode:=((DoWeights==1)*(isTthSample==1)*0.972+(DoWeights==1)*(isTthSample==0)*0.968+(DoWeights==0)*1.0)",
        "L1ScaleFactor_j5_tge3_ttbnode:=((DoWeights==1)*(isTthSample==1)*0.978+(DoWeights==1)*(isTthSample==0)*0.976+(DoWeights==0)*1.0)",
        "L1ScaleFactor_j5_tge3_tt2bnode:=((DoWeights==1)*(isTthSample==1)*0.972+(DoWeights==1)*(isTthSample==0)*0.966+(DoWeights==0)*1.0)",
        "L1ScaleFactor_j5_tge3_ttccnode:=((DoWeights==1)*(isTthSample==1)*0.974+(DoWeights==1)*(isTthSample==0)*0.968+(DoWeights==0)*1.0)",
        "L1ScaleFactor_j5_tge3_ttlfnode:=((DoWeights==1)*(isTthSample==1)*0.975+(DoWeights==1)*(isTthSample==0)*0.976+(DoWeights==0)*1.0)",

        "L1ScaleFactor_jge6_tge3_ttHnode:=((DoWeights==1)*(isTthSample==1)*0.975+(DoWeights==1)*(isTthSample==0)*0.969+(DoWeights==0)*1.0)",
        "L1ScaleFactor_jge6_tge3_ttbbnode:=((DoWeights==1)*(isTthSample==1)*0.965+(DoWeights==1)*(isTthSample==0)*0.962+(DoWeights==0)*1.0)",
        "L1ScaleFactor_jge6_tge3_ttbnode:=((DoWeights==1)*(isTthSample==1)*0.973+(DoWeights==1)*(isTthSample==0)*0.969+(DoWeights==0)*1.0)",
        "L1ScaleFactor_jge6_tge3_tt2bnode:=((DoWeights==1)*(isTthSample==1)*0.966+(DoWeights==1)*(isTthSample==0)*0.956+(DoWeights==0)*1.0)",
        "L1ScaleFactor_jge6_tge3_ttccnode:=((DoWeights==1)*(isTthSample==1)*0.966+(DoWeights==1)*(isTthSample==0)*0.957+(DoWeights==0)*1.0)",
        "L1ScaleFactor_jge6_tge3_ttlfnode:=((DoWeights==1)*(isTthSample==1)*0.971+(DoWeights==1)*(isTthSample==0)*0.969+(DoWeights==0)*1.0)",
        ]

    return addVars


