stages: 
    - produceHistosDataCards
    

variables:
  GIT_DEPTH: "3"


before_script:
    - echo "Gitlab User " ${GITLAB_USER_ID}
    - export CI_HOME=${CI_PROJECT_DIR}
    - export SCRAM_ARCH="slc6_amd64_gcc530"
    - export CMSSW_VERSION="CMSSW_8_0_26_patch2"
    - source /cvmfs/cms.cern.ch/cmsset_default.sh
    - cd /nfs/dust/cms/user/${USER}/gitlab-ci/${CMSSW_VERSION}/src
    - eval `scramv1 runtime -sh`
    - scram b -j 12
    - cd $CI_HOME

plot_LimitsSpring17v3_modified:
    tags:
        - naf
        - ssh
    stage: produceHistosDataCards
    script:
        - echo "Gitlab User " ${GITLAB_USER_ID}
        - set -x 
        - cd $CI_HOME
        - python plot_LimitsAll_v19.py
        - echo "Store outputs on webpage"
        - mkdir -p ~/www/pyroot-plotscripts-base/${CI_COMMIT_REF_NAME}/${CI_PIPELINE_ID}
        - cp $CI_HOME/limits_JetTagBDT_v17/*.pdf ~/www/pyroot-plotscripts-base/${CI_COMMIT_REF_SLUG}/${CI_PIPELINE_ID}/
        - cp $CI_HOME/limits_JetTagBDT_v17/limits_JetTagBDT_v17/*.pdf ~/www/pyroot-plotscripts-base/${CI_COMMIT_REF_SLUG}/${CI_PIPELINE_ID}/
        - cp $CI_HOME/limits_JetTagBDT_v17/limits_JetTagBDT_v17/*.pdf ~/www/pyroot-plotscripts-base/${CI_COMMIT_REF_SLUG}/${CI_PIPELINE_ID}/

        
