prefix="limits_All_v22_"

nameMap={
"datacard_ljets_jge6_tge4_hdecay": "LJ #geq 6 jets, #geq 4 b-tags",
"datacard_ljets_jge6_tge4_low_hdecay": "LJ #geq 6 jets, #geq 4 b-tags low BDT",
"datacard_ljets_jge6_tge4_high_hdecay": "LJ #geq 6 jets, #geq 4 b-tags high BDT",
"datacard_ljets_jge6_t3_hdecay": "LJ #geq 6 jets, 3 b-tags",
"datacard_ljets_jge6_t3_low_hdecay": "LJ #geq 6 jets, 3 b-tags low BDT",
"datacard_ljets_jge6_t3_high_hdecay": "LJ #geq 6 jets, 3 b-tags high  BDT",
"datacard_ljets_j5_tge4_hdecay": "LJ 5 jets, #geq 4 b-tags",
"datacard_ljets_j5_tge4_low_hdecay": "LJ 5 jets, #geq 4 b-tags low BDT",
"datacard_ljets_j5_tge4_high_hdecay": "LJ 5 jets, #geq 4 b-tags high BDT",
"datacard_ljets_j4_t4_hdecay": "LJ 4 jets, 4 b-tags",
"datacard_ljets_j4_t4_low_hdecay": "LJ 4 jets, 4 b-tags low BDT",
"datacard_ljets_j4_t4_high_hdecay": "LJ 4 jets, 4 b-tags high BDT",
"datacard_ljets_j5_t3_hdecay": "LJ 4 jets, 3 b-tags",
"datacard_ljets_j4_t3_hdecay": "LJ 5 jets, 3 b-tags",
"datacard_ljets_jge6_t2_hdecay": "LJ #geq 6 jets, 2 b-tags",
"ttH_hbb_13TeV_dl_3j3t": "DL 3 jets, 3 b-tags ",
"ttH_hbb_13TeV_dl_ge4j3t_both": "DL #geq 4 jets, 3 b-tags",
"ttH_hbb_13TeV_dl_ge4j3t_high": "DL #geq 4 jets, 3 b-tags high BDT",
"ttH_hbb_13TeV_dl_ge4j3t_low": "DL #geq 4 jets, 3 b-tags low BDT",
"ttH_hbb_13TeV_dl_ge4jge4t_both": "DL #geq 4 jets, #geq 4 b-tags",
"ttH_hbb_13TeV_dl_ge4jge4t_high": "DL #geq 4 jets, #geq 4 b-tags high BDT",
"ttH_hbb_13TeV_dl_ge4jge4t_low": "DL #geq 4 jets, #geq 4 b-tags low BDT",
"DL_BDTonly": "DL BDT-only",
"DL_2D": "DL BDT+MEM",
"SL_BDTonly": "LJ BDT-only",
"SL_2D": "LJ BDT+MEM",
"combined_2D": "DL+LJ BDT+MEM",
"combined_BDTonly": "DL+LJ BDT-only",
"combined_SLDNN_DL2D": "DL BDT+MEM and LJ DNN",
"SL_DNN":  "LJ DNN",
"DL_DNN":  "DL DNN",
"combined_DNNonly": "DL+LJ DNN",
"SL_DNN_4j_ge3t": "LJ 4 jets, #geq 3-btags DNN",
"SL_DNN_5j_ge3t": "LJ 5 jets, #geq 3-btags DNN",
"SL_DNN_ge6j_ge3t": "LJ #geq6 jets, #geq 3-btags DNN",
"DL_DNN_ge4j_ge3t": "LJ #geq 4 jets, #geq 3-btags DNN",
"DL_DNN_3j_ge3t": "LJ 3 jets, 3-btags DNN",
}

cateNameMap={
  "finaldiscr_ljets_jge6_tge4": "LJ #geq 6 jets, #geq 4 b-tags",
"finaldiscr_ljets_jge6_tge4_low": "LJ #geq 6 jets, #geq 4 b-tags low BDT",
"finaldiscr_ljets_jge6_tge4_high": "LJ #geq 6 jets, #geq 4 b-tags high BDT",
"finaldiscr_ljets_jge6_t3": "LJ #geq 6 jets, 3 b-tags",
"finaldiscr_ljets_jge6_t3_low": "LJ #geq 6 jets, 3 b-tags low BDT",
"finaldiscr_ljets_jge6_t3_high": "LJ #geq 6 jets, 3 b-tags high  BDT",
"finaldiscr_ljets_j5_tge4": "LJ 5 jets, #geq 4 b-tags",
"finaldiscr_ljets_j5_tge4_low": "LJ 5 jets, #geq 4 b-tags low BDT",
"finaldiscr_ljets_j5_tge4_high": "LJ 5 jets, #geq 4 b-tags high BDT",
"finaldiscr_ljets_j4_t4": "LJ 4 jets, 4 b-tags",
"finaldiscr_ljets_j4_t4_low": "LJ 4 jets, 4 b-tags low BDT",
"finaldiscr_ljets_j4_t4_high": "LJ 4 jets, 4 b-tags high BDT",
"finaldiscr_ljets_j5_t3": "LJ 4 jets, 3 b-tags",
"finaldiscr_ljets_j4_t3": "LJ 5 jets, 3 b-tags",
"finaldiscr_ljets_jge6_t2": "LJ #geq 6 jets, 2 b-tags",
"dl_3j3t_BDT": "DL 3 jets, 3 b-tags ",
"dl_ge4j3t_BDT": "DL #geq 4 jets, 3 b-tags",
"dl_ge4j3t_high_BDT": "DL #geq 4 jets, 3 b-tags high BDT",
"dl_ge4j3t_low_BDT": "DL #geq 4 jets, 3 b-tags low BDT",
"dl_ge4jge4t_BDT": "DL #geq 4 jets, #geq 4 b-tags",
"dl_ge4jge4t_high_BDT": "DL #geq 4 jets, #geq 4 b-tags high BDT",
"dl_ge4jge4t_low_BDT": "DL #geq 4 jets, #geq 4 b-tags low BDT",
}



inputCards={
"datacard_ljets_j4_t2_hdecay" : [],
"datacard_ljets_j4_t3_BLR_hdecay" : [],
"datacard_ljets_j4_t3_hdecay" : ["SL_2D","SL_BDTonly","combined_BDTonly","combined_2D"],
"datacard_ljets_j4_t4_hdecay" : ["SL_BDTonly","combined_BDTonly"],
"datacard_ljets_j4_t4_high_hdecay" : ["SL_2D","combined_2D"],
"datacard_ljets_j4_t4_low_hdecay" : ["SL_2D","combined_2D"],
"datacard_ljets_j4_t4_MEMONLY_hdecay" : [],
"datacard_ljets_j4_t4_ttbbOpt_hdecay" : [],
"datacard_ljets_j4_t4_ttbbOpt_high_hdecay" : [],
"datacard_ljets_j4_t4_ttbbOpt_low_hdecay" : [],
#"datacard_ljets_j4_tge3_tt2bnode_hdecay" : ["SL_KITDNN"],
#"datacard_ljets_j4_tge3_ttbbnode_hdecay" : ["SL_KITDNN"],
#"datacard_ljets_j4_tge3_ttbnode_hdecay" : ["SL_KITDNN"],
#"datacard_ljets_j4_tge3_ttccnode_hdecay" : ["SL_KITDNN"],
#"datacard_ljets_j4_tge3_ttHnode_hdecay" : ["SL_KITDNN"],
#"datacard_ljets_j4_tge3_ttlfnode_hdecay" : ["SL_KITDNN"] ,
"datacard_ljets_j5_t2_hdecay" : [],
"datacard_ljets_j5_t3_BLR_hdecay" : [],
"datacard_ljets_j5_t3_hdecay" : ["SL_2D","SL_BDTonly","combined_BDTonly","combined_2D"],
#"datacard_ljets_j5_tge3_tt2bnode_hdecay" : ["SL_KITDNN"] ,
#"datacard_ljets_j5_tge3_ttbbnode_hdecay" : ["SL_KITDNN"] ,
#"datacard_ljets_j5_tge3_ttbnode_hdecay" : ["SL_KITDNN"] ,
#"datacard_ljets_j5_tge3_ttccnode_hdecay" : ["SL_KITDNN"] ,
#"datacard_ljets_j5_tge3_ttHnode_hdecay" : ["SL_KITDNN"] ,
#"datacard_ljets_j5_tge3_ttlfnode_hdecay" : ["SL_KITDNN"] ,
"datacard_ljets_j5_tge4_hdecay" : ["SL_BDTonly","combined_BDTonly"],
"datacard_ljets_j5_tge4_high_hdecay" : ["SL_2D","combined_2D"],
"datacard_ljets_j5_tge4_low_hdecay" : ["SL_2D","combined_2D"],
"datacard_ljets_j5_tge4_MEMONLY_hdecay" : [],
"datacard_ljets_j5_tge4_ttbbOpt_hdecay" : [],
"datacard_ljets_j5_tge4_ttbbOpt_high_hdecay" : [],
"datacard_ljets_j5_tge4_ttbbOpt_low_hdecay" : [],
"datacard_ljets_jge6_t2_BLR_hdecay" : [],
"datacard_ljets_jge6_t2_hdecay" : [],
"datacard_ljets_jge6_t3_BLR_hdecay" : [],
"datacard_ljets_jge6_t3_hdecay" : ["SL_BDTonly","combined_BDTonly"],
"datacard_ljets_jge6_t3_high_hdecay" : ["SL_2D","combined_2D"],
"datacard_ljets_jge6_t3_low_hdecay" : ["SL_2D","combined_2D"],
"datacard_ljets_jge6_t3_MEMONLY_hdecay" : [],
"datacard_ljets_jge6_t3_ttbbOpt_hdecay" : [],
"datacard_ljets_jge6_t3_ttbbOpt_high_hdecay" : [],
"datacard_ljets_jge6_t3_ttbbOpt_low_hdecay" : [],
#"datacard_ljets_jge6_tge3_tt2bnode_hdecay" : ["SL_KITDNN"] ,
#"datacard_ljets_jge6_tge3_ttbbnode_hdecay" : ["SL_KITDNN"] ,
#"datacard_ljets_jge6_tge3_ttbnode_hdecay" : ["SL_KITDNN"] ,
#"datacard_ljets_jge6_tge3_ttccnode_hdecay" : ["SL_KITDNN"] ,
#"datacard_ljets_jge6_tge3_ttHnode_hdecay" : ["SL_KITDNN"] ,
#"datacard_ljets_jge6_tge3_ttlfnode_hdecay" : ["SL_KITDNN"] ,
"datacard_ljets_jge6_tge4_hdecay" : ["SL_BDTonly","combined_BDTonly"],
"datacard_ljets_jge6_tge4_high_hdecay" : ["SL_2D","combined_2D"],
"datacard_ljets_jge6_tge4_low_hdecay" : ["SL_2D","combined_2D"],
"datacard_ljets_jge6_tge4_MEMONLY_hdecay" : [],
"datacard_ljets_jge6_tge4_ttbbOpt_hdecay" : [],
"datacard_ljets_jge6_tge4_ttbbOpt_high_hdecay" : [],
"datacard_ljets_jge6_tge4_ttbbOpt_low_hdecay" : [],
"ttH_hbb_13TeV_dl_3j3t" : ["DL_BDTonly","DL_2D","combined_2D","combined_BDTonly","combined_SLDNN_DL2D"],
"ttH_hbb_13TeV_dl_ge4j3t_both" : ["DL_BDTonly","combined_BDTonly"],
"ttH_hbb_13TeV_dl_ge4j3t_high" : ["DL_2D","combined_2D","combined_SLDNN_DL2D"],
"ttH_hbb_13TeV_dl_ge4j3t_low" : ["DL_2D","combined_2D","combined_SLDNN_DL2D"],
"ttH_hbb_13TeV_dl_ge4jge4t_both" : ["DL_BDTonly","combined_BDTonly"],
"ttH_hbb_13TeV_dl_ge4jge4t_high" : ["DL_2D","combined_2D","combined_SLDNN_DL2D"],
"ttH_hbb_13TeV_dl_ge4jge4t_low" : ["DL_2D","combined_2D","combined_SLDNN_DL2D"],
"e_eq4j_ge3b_cc_v6b_ttH125_bb__MVA_cc_dnn_ttH_SL_v6b" : ["SL_DNN","SL_DNN_4j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"e_eq4j_ge3b_cc_v6b_ttJets_2b__MVA_cc_dnn_tt2b_SL_v6b" : ["SL_DNN","SL_DNN_4j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"e_eq4j_ge3b_cc_v6b_ttJets_b__MVA_cc_dnn_ttb_SL_v6b" : ["SL_DNN","SL_DNN_4j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"e_eq4j_ge3b_cc_v6b_ttJets_bb__MVA_cc_dnn_ttbb_SL_v6b" : ["SL_DNN","SL_DNN_4j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"e_eq4j_ge3b_cc_v6b_ttJets_cc__MVA_cc_dnn_ttcc_SL_v6b" : ["SL_DNN","SL_DNN_4j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"e_eq4j_ge3b_cc_v6b_ttJets_lf__MVA_cc_dnn_ttlf_SL_v6b" : ["SL_DNN","SL_DNN_4j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"e_eq5j_ge3b_cc_v6b_ttH125_bb__MVA_cc_dnn_ttH_SL_v6b" : ["SL_DNN","SL_DNN_5j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"e_eq5j_ge3b_cc_v6b_ttJets_2b__MVA_cc_dnn_tt2b_SL_v6b" : ["SL_DNN","SL_DNN_5j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"e_eq5j_ge3b_cc_v6b_ttJets_b__MVA_cc_dnn_ttb_SL_v6b" : ["SL_DNN","SL_DNN_5j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"e_eq5j_ge3b_cc_v6b_ttJets_bb__MVA_cc_dnn_ttbb_SL_v6b" : ["SL_DNN","SL_DNN_5j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"e_eq5j_ge3b_cc_v6b_ttJets_cc__MVA_cc_dnn_ttcc_SL_v6b" : ["SL_DNN","SL_DNN_5j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"e_eq5j_ge3b_cc_v6b_ttJets_lf__MVA_cc_dnn_ttlf_SL_v6b" : ["SL_DNN","SL_DNN_5j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"e_ge6j_ge2b_cc_v6b_ttH125_bb__MVA_cc_dnn_ttH_SL_v6b" : ["SL_DNN","SL_DNN_ge6j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"e_ge6j_ge2b_cc_v6b_ttJets_2b__MVA_cc_dnn_tt2b_SL_v6b" : ["SL_DNN","SL_DNN_ge6j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"e_ge6j_ge2b_cc_v6b_ttJets_b__MVA_cc_dnn_ttb_SL_v6b" : ["SL_DNN","SL_DNN_ge6j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"e_ge6j_ge2b_cc_v6b_ttJets_bb__MVA_cc_dnn_ttbb_SL_v6b" : ["SL_DNN","SL_DNN_ge6j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"e_ge6j_ge2b_cc_v6b_ttJets_cc__MVA_cc_dnn_ttcc_SL_v6b" : ["SL_DNN","SL_DNN_ge6j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"e_ge6j_ge2b_cc_v6b_ttJets_lf__MVA_cc_dnn_ttlf_SL_v6b" : ["SL_DNN","SL_DNN_ge6j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"ee_eq3j_eq3b_cc_v3a_ttH125_bb__MVA_cc_dnn_ttH_DL_v3a" : ["DL_DNN","DL_DNN_3j_ge3t","combined_DNNonly"],
"ee_eq3j_eq3b_cc_v3a_ttJets_2b__MVA_cc_dnn_tt2b_DL_v3a" : ["DL_DNN","DL_DNN_3j_ge3t","combined_DNNonly"],
"ee_eq3j_eq3b_cc_v3a_ttJets_b__MVA_cc_dnn_ttb_DL_v3a" : ["DL_DNN","DL_DNN_3j_ge3t","combined_DNNonly"],
"ee_eq3j_eq3b_cc_v3a_ttJets_bb__MVA_cc_dnn_ttbb_DL_v3a" : ["DL_DNN","DL_DNN_3j_ge3t","combined_DNNonly"],
"ee_eq3j_eq3b_cc_v3a_ttJets_cc__MVA_cc_dnn_ttcc_DL_v3a" : ["DL_DNN","DL_DNN_3j_ge3t","combined_DNNonly"],
"ee_eq3j_eq3b_cc_v3a_ttJets_lf__MVA_cc_dnn_ttlf_DL_v3a" : ["DL_DNN","DL_DNN_3j_ge3t","combined_DNNonly"],
"ee_ge4j_ge3b_cc_v3a_ttH125_bb__MVA_cc_dnn_ttH_DL_v3a" : ["DL_DNN","DL_DNN_ge4j_ge3t","combined_DNNonly"],
"ee_ge4j_ge3b_cc_v3a_ttJets_2b__MVA_cc_dnn_tt2b_DL_v3a" : ["DL_DNN","DL_DNN_ge4j_ge3t","combined_DNNonly"],
"ee_ge4j_ge3b_cc_v3a_ttJets_b__MVA_cc_dnn_ttb_DL_v3a" : ["DL_DNN","DL_DNN_ge4j_ge3t","combined_DNNonly"],
"ee_ge4j_ge3b_cc_v3a_ttJets_bb__MVA_cc_dnn_ttbb_DL_v3a" : ["DL_DNN","DL_DNN_ge4j_ge3t","combined_DNNonly"],
"ee_ge4j_ge3b_cc_v3a_ttJets_cc__MVA_cc_dnn_ttcc_DL_v3a" : ["DL_DNN","DL_DNN_ge4j_ge3t","combined_DNNonly"],
"ee_ge4j_ge3b_cc_v3a_ttJets_lf__MVA_cc_dnn_ttlf_DL_v3a" : ["DL_DNN","DL_DNN_ge4j_ge3t","combined_DNNonly"],
"emu_eq3j_eq3b_cc_v3a_ttH125_bb__MVA_cc_dnn_ttH_DL_v3a" : ["DL_DNN","DL_DNN_3j_ge3t","combined_DNNonly"],
"emu_eq3j_eq3b_cc_v3a_ttJets_2b__MVA_cc_dnn_tt2b_DL_v3a" : ["DL_DNN","DL_DNN_3j_ge3t","combined_DNNonly"],
"emu_eq3j_eq3b_cc_v3a_ttJets_b__MVA_cc_dnn_ttb_DL_v3a" : ["DL_DNN","DL_DNN_3j_ge3t","combined_DNNonly"],
"emu_eq3j_eq3b_cc_v3a_ttJets_bb__MVA_cc_dnn_ttbb_DL_v3a" : ["DL_DNN","DL_DNN_3j_ge3t","combined_DNNonly"],
"emu_eq3j_eq3b_cc_v3a_ttJets_cc__MVA_cc_dnn_ttcc_DL_v3a" : ["DL_DNN","DL_DNN_3j_ge3t","combined_DNNonly"],
"emu_eq3j_eq3b_cc_v3a_ttJets_lf__MVA_cc_dnn_ttlf_DL_v3a" : ["DL_DNN","DL_DNN_3j_ge3t","combined_DNNonly"],
"emu_ge4j_ge3b_cc_v3a_ttH125_bb__MVA_cc_dnn_ttH_DL_v3a" : ["DL_DNN","DL_DNN_ge4j_ge3t","combined_DNNonly"],
"emu_ge4j_ge3b_cc_v3a_ttJets_2b__MVA_cc_dnn_tt2b_DL_v3a" : ["DL_DNN","DL_DNN_ge4j_ge3t","combined_DNNonly"],
"emu_ge4j_ge3b_cc_v3a_ttJets_b__MVA_cc_dnn_ttb_DL_v3a" : ["DL_DNN","DL_DNN_ge4j_ge3t","combined_DNNonly"],
"emu_ge4j_ge3b_cc_v3a_ttJets_bb__MVA_cc_dnn_ttbb_DL_v3a" : ["DL_DNN","DL_DNN_ge4j_ge3t","combined_DNNonly"],
"emu_ge4j_ge3b_cc_v3a_ttJets_cc__MVA_cc_dnn_ttcc_DL_v3a" : ["DL_DNN","DL_DNN_ge4j_ge3t","combined_DNNonly"],
"emu_ge4j_ge3b_cc_v3a_ttJets_lf__MVA_cc_dnn_ttlf_DL_v3a" : ["DL_DNN","DL_DNN_ge4j_ge3t","combined_DNNonly"],
"mu_eq4j_ge3b_cc_v6b_ttH125_bb__MVA_cc_dnn_ttH_SL_v6b" : ["SL_DNN","SL_DNN_4j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"mu_eq4j_ge3b_cc_v6b_ttJets_2b__MVA_cc_dnn_tt2b_SL_v6b" : ["SL_DNN","SL_DNN_4j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"mu_eq4j_ge3b_cc_v6b_ttJets_b__MVA_cc_dnn_ttb_SL_v6b" : ["SL_DNN","SL_DNN_4j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"mu_eq4j_ge3b_cc_v6b_ttJets_bb__MVA_cc_dnn_ttbb_SL_v6b" : ["SL_DNN","SL_DNN_4j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"mu_eq4j_ge3b_cc_v6b_ttJets_cc__MVA_cc_dnn_ttcc_SL_v6b" : ["SL_DNN","SL_DNN_4j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"mu_eq4j_ge3b_cc_v6b_ttJets_lf__MVA_cc_dnn_ttlf_SL_v6b" : ["SL_DNN","SL_DNN_4j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"mu_eq5j_ge3b_cc_v6b_ttH125_bb__MVA_cc_dnn_ttH_SL_v6b" : ["SL_DNN","SL_DNN_5j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"mu_eq5j_ge3b_cc_v6b_ttJets_2b__MVA_cc_dnn_tt2b_SL_v6b" : ["SL_DNN","SL_DNN_5j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"mu_eq5j_ge3b_cc_v6b_ttJets_b__MVA_cc_dnn_ttb_SL_v6b" : ["SL_DNN","SL_DNN_5j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"mu_eq5j_ge3b_cc_v6b_ttJets_bb__MVA_cc_dnn_ttbb_SL_v6b" : ["SL_DNN","SL_DNN_5j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"mu_eq5j_ge3b_cc_v6b_ttJets_cc__MVA_cc_dnn_ttcc_SL_v6b" : ["SL_DNN","SL_DNN_5j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"mu_eq5j_ge3b_cc_v6b_ttJets_lf__MVA_cc_dnn_ttlf_SL_v6b" : ["SL_DNN","SL_DNN_5j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"mu_ge6j_ge2b_cc_v6b_ttH125_bb__MVA_cc_dnn_ttH_SL_v6b" : ["SL_DNN","SL_DNN_ge6j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"mu_ge6j_ge2b_cc_v6b_ttJets_2b__MVA_cc_dnn_tt2b_SL_v6b" : ["SL_DNN","SL_DNN_ge6j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"mu_ge6j_ge2b_cc_v6b_ttJets_b__MVA_cc_dnn_ttb_SL_v6b" : ["SL_DNN","SL_DNN_ge6j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"mu_ge6j_ge2b_cc_v6b_ttJets_bb__MVA_cc_dnn_ttbb_SL_v6b" : ["SL_DNN","SL_DNN_ge6j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"mu_ge6j_ge2b_cc_v6b_ttJets_cc__MVA_cc_dnn_ttcc_SL_v6b" : ["SL_DNN","SL_DNN_ge6j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"mu_ge6j_ge2b_cc_v6b_ttJets_lf__MVA_cc_dnn_ttlf_SL_v6b" : ["SL_DNN","SL_DNN_ge6j_ge3t","combined_SLDNN_DL2D","combined_DNNonly"],
"mumu_eq3j_eq3b_cc_v3a_ttH125_bb__MVA_cc_dnn_ttH_DL_v3a" : ["DL_DNN","DL_DNN_3j_ge3t","combined_DNNonly"],
"mumu_eq3j_eq3b_cc_v3a_ttJets_2b__MVA_cc_dnn_tt2b_DL_v3a" : ["DL_DNN","DL_DNN_3j_ge3t","combined_DNNonly"],
"mumu_eq3j_eq3b_cc_v3a_ttJets_b__MVA_cc_dnn_ttb_DL_v3a" : ["DL_DNN","DL_DNN_3j_ge3t","combined_DNNonly"],
"mumu_eq3j_eq3b_cc_v3a_ttJets_bb__MVA_cc_dnn_ttbb_DL_v3a" : ["DL_DNN","DL_DNN_3j_ge3t","combined_DNNonly"],
"mumu_eq3j_eq3b_cc_v3a_ttJets_cc__MVA_cc_dnn_ttcc_DL_v3a" : ["DL_DNN","DL_DNN_3j_ge3t","combined_DNNonly"],
"mumu_eq3j_eq3b_cc_v3a_ttJets_lf__MVA_cc_dnn_ttlf_DL_v3a" : ["DL_DNN","DL_DNN_3j_ge3t","combined_DNNonly"],
"mumu_ge4j_ge3b_cc_v3a_ttH125_bb__MVA_cc_dnn_ttH_DL_v3a" : ["DL_DNN","DL_DNN_ge4j_ge3t","combined_DNNonly"],
"mumu_ge4j_ge3b_cc_v3a_ttJets_2b__MVA_cc_dnn_tt2b_DL_v3a" : ["DL_DNN","DL_DNN_ge4j_ge3t","combined_DNNonly"],
"mumu_ge4j_ge3b_cc_v3a_ttJets_b__MVA_cc_dnn_ttb_DL_v3a" : ["DL_DNN","DL_DNN_ge4j_ge3t","combined_DNNonly"],
"mumu_ge4j_ge3b_cc_v3a_ttJets_bb__MVA_cc_dnn_ttbb_DL_v3a" : ["DL_DNN","DL_DNN_ge4j_ge3t","combined_DNNonly"],
"mumu_ge4j_ge3b_cc_v3a_ttJets_cc__MVA_cc_dnn_ttcc_DL_v3a" : ["DL_DNN","DL_DNN_ge4j_ge3t","combined_DNNonly"],
"mumu_ge4j_ge3b_cc_v3a_ttJets_lf__MVA_cc_dnn_ttlf_DL_v3a" : ["DL_DNN","DL_DNN_ge4j_ge3t","combined_DNNonly"],
}
