#!/bin/bash
qsub -l h=bird* -hard -l os=sld6 -l h_vmem=4000M -l s_vmem=4000M -l cvmfs -cwd -S /bin/bash -o /nfs/dust/cms/user/kelmorab/limitstudies0111/pyroot-plotscripts/GregorBinning/newPlots/pyroot-plotscripts/ANplots/HybridLimit_clean/logs/\$JOB_NAME.o\$JOB_ID -e logs/\$JOB_NAME.e\$JOB_ID -q 'default.q' ToyMC1.sh
qsub -l h=bird* -hard -l os=sld6 -l h_vmem=4000M -l s_vmem=4000M -l cvmfs -cwd -S /bin/bash -o /nfs/dust/cms/user/kelmorab/limitstudies0111/pyroot-plotscripts/GregorBinning/newPlots/pyroot-plotscripts/ANplots/HybridLimit_clean/logs/\$JOB_NAME.o\$JOB_ID -e logs/\$JOB_NAME.e\$JOB_ID -q 'default.q' ToyMC2.sh
qsub -l h=bird* -hard -l os=sld6 -l h_vmem=4000M -l s_vmem=4000M -l cvmfs -cwd -S /bin/bash -o /nfs/dust/cms/user/kelmorab/limitstudies0111/pyroot-plotscripts/GregorBinning/newPlots/pyroot-plotscripts/ANplots/HybridLimit_clean/logs/\$JOB_NAME.o\$JOB_ID -e logs/\$JOB_NAME.e\$JOB_ID -q 'default.q' ToyMC3.sh
qsub -l h=bird* -hard -l os=sld6 -l h_vmem=4000M -l s_vmem=4000M -l cvmfs -cwd -S /bin/bash -o /nfs/dust/cms/user/kelmorab/limitstudies0111/pyroot-plotscripts/GregorBinning/newPlots/pyroot-plotscripts/ANplots/HybridLimit_clean/logs/\$JOB_NAME.o\$JOB_ID -e logs/\$JOB_NAME.e\$JOB_ID -q 'default.q' ToyMC4.sh
qsub -l h=bird* -hard -l os=sld6 -l h_vmem=4000M -l s_vmem=4000M -l cvmfs -cwd -S /bin/bash -o /nfs/dust/cms/user/kelmorab/limitstudies0111/pyroot-plotscripts/GregorBinning/newPlots/pyroot-plotscripts/ANplots/HybridLimit_clean/logs/\$JOB_NAME.o\$JOB_ID -e logs/\$JOB_NAME.e\$JOB_ID -q 'default.q' ToyMC5.sh
qsub -l h=bird* -hard -l os=sld6 -l h_vmem=4000M -l s_vmem=4000M -l cvmfs -cwd -S /bin/bash -o /nfs/dust/cms/user/kelmorab/limitstudies0111/pyroot-plotscripts/GregorBinning/newPlots/pyroot-plotscripts/ANplots/HybridLimit_clean/logs/\$JOB_NAME.o\$JOB_ID -e logs/\$JOB_NAME.e\$JOB_ID -q 'default.q' ToyMC6.sh
qsub -l h=bird* -hard -l os=sld6 -l h_vmem=4000M -l s_vmem=4000M -l cvmfs -cwd -S /bin/bash -o /nfs/dust/cms/user/kelmorab/limitstudies0111/pyroot-plotscripts/GregorBinning/newPlots/pyroot-plotscripts/ANplots/HybridLimit_clean/logs/\$JOB_NAME.o\$JOB_ID -e logs/\$JOB_NAME.e\$JOB_ID -q 'default.q' ToyMC7.sh
qsub -l h=bird* -hard -l os=sld6 -l h_vmem=4000M -l s_vmem=4000M -l cvmfs -cwd -S /bin/bash -o /nfs/dust/cms/user/kelmorab/limitstudies0111/pyroot-plotscripts/GregorBinning/newPlots/pyroot-plotscripts/ANplots/HybridLimit_clean/logs/\$JOB_NAME.o\$JOB_ID -e logs/\$JOB_NAME.e\$JOB_ID -q 'default.q' ToyMC8.sh
