def getAddVars():
    addVars = [
	"N_GenTopLep",
	"GenHiggs_DecProd1_PDGID",
        "Jet_Pt",
        "Muon_Pt",
        "Electron_Pt",
        "Jet_Eta",
        "Muon_Eta",
        "Electron_Eta",
        "Muon_Pt_BeForeRC",
        "Electron_Pt_BeforeRun2Calibration",
        "Electron_Eta_Supercluster",
        "Jet_CSV",
        "Jet_Flav",
        "N_Jets",
        "Jet_E",
        "Jet_Phi",
        "Jet_M",
        "Evt_Pt_PrimaryLepton:=LooseLepton_Pt[0]",
        "Evt_E_PrimaryLepton:=LooseLepton_E[0]",
        "Evt_M_PrimaryLepton:=LooseLepton_M[0]",
        "Evt_Phi_PrimaryLepton:=LooseLepton_Phi[0]",
        "Evt_Eta_PrimaryLepton:=LooseLepton_Eta[0]",
        "Evt_MET_Pt",
        "Evt_HT_jets:=1.",
        #"Weight_CSV",
        #"Weight_CSVLFup",
        #"Weight_CSVLFdown",
        #"Weight_CSVHFup",
        #"Weight_CSVHFdown",
        #"Weight_CSVHFStats1up",
       # "Weight_CSVHFStats1down",
       # "Weight_CSVLFStats1down",
       # "Weight_CSVHFStats2up",
       # "Weight_CSVHFStats2down",
       # "Weight_CSVLFStats2up",
       # "Weight_CSVLFStats2down",
       # "Weight_CSVCErr1down",
       # "Weight_CSVCErr2up",
        #"Weight_CSVCErr2down",
        ]

    return addVars
